#version: '3.8'
services: 
    mysql:    
      container_name: mysql
      image: mysql:8 
      ports:     
      - "3306:3306"   
      volumes:      
      - mysql-volume:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: "Test@123"
        MYSQL_DATABASE: "bankappdb"

    bankapp:
      container_name: bankapp
      image: ganesh1326/goldencatbankapp:latest
      ports:
      - "8081:8080"
      environment:
        SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
        SPRING_DATASOURCE_USERNAME: "root"
        SPRING_DATASOURCE_PASSWORD: "Test@123"
volumes:
  mysql-volume:
