name: GoldenCatBankApp-CI

on:
  push:
    branches: 
    - main 
    paths-ignore:
    - 'ds.yaml'

jobs:
  Code-Checkout:
    runs-on: self-hosted
    steps:
    - name: Code Checkout
      uses: actions/checkout@v4
      
  Setup-JAVA-17:  
    runs-on: self-hosted
    needs: Code-Checkout
    steps:
    - name: Set up JDK 17
      run: sudo apt-get install openjdk-17-jdk -y

  Setup-Maven-and-build:  
    runs-on: self-hosted
    needs: Setup-JAVA-17
    steps:      
    - name: Setup up maven
      run: sudo apt-get install maven -y
    - name: Build with Maven
      run: mvn package

